Cadeia D
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
D  115    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
CYSHI PRO   LEU   MET   VAL   LYS   VAL   LEU   ASP   ALA  
VAL   ARG   GLY   SER   PRO   ALA   ILE   ASN   VAL   ALA  
VAL   HISD  VAL   PHE   ARG   LYS   ALA   ALA   ASP   ASP  
THR   TRP   GLU   PRO   PHE   ALA   SER   GLY   LYS   THR  
SER   GLU   SER   GLY   GLU   LEU   HISP  GLY   LEU   THR  
THR   GLU   GLU   GLU   PHE   VAL   GLU   GLY   ILE   TYR  
LYS   VAL   GLU   ILE   ASP   THR   LYS   SER   TYR   TRP  
LYS   ALA   LEU   GLY   ILE   SER   PRO   PHE   HISE  GLU  
HISP  ALA   GLU   VAL   VAL   PHE   THR   ALA   ASN   ASP  
SER   GLY   PRO   ARG   ARG   TYR   THR   ILE   ALA   ALA  
LEU   LEU   SER   PRO   TYR   SER   TYR   SER   THR   THR  
ALA   VAL   VAL   THR   ASNT                               
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                       

