Cadeia H
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
H  218    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
GLUI  VAL   LYS   LEU   VAL   GLU   SER   GLY   GLY   GLY  
LEU   GLY   GLN   PRO   GLY   GLY   SER   LEU   ARG   LEU  
SER   CYSS  ALA   THR   SER   GLY   PHE   THR   PHE   THR  
ASP   TYR   TYR   PHE   ASN   TRP   ALA   ARG   GLN   PRO  
PRO   GLY   LYS   ALA   LEU   GLU   TRP   LEU   GLY   PHE  
ILE   ARG   ASN   LYS   ALA   LYS   GLY   TYR   THR   THR  
GLU   TYR   SER   ALA   SER   VAL   LYS   GLY   ARG   PHE  
THR   ILE   SER   ARG   ASP   ASN   SER   GLN   GLY   ILE  
LEU   TYR   LEU   GLN   MET   ASN   THR   LEU   ARG   ALA  
GLU   ASP   SER   ALA   THR   TYR   TYR   CYSS  ALA   ARG  
TRP   GLY   SER   TYR   ALA   MET   ASP   TYR   TRP   GLY  
GLN   GLY   THR   SER   VAL   THR   VAL   SER   SER   ALA  
LYS   THR   THR   PRO   PRO   SER   VAL   TYR   PRO   LEU  
ALA   PRO   GLY   SER   ALA   ALA   GLN   THR   ASN   SER  
MET   VAL   THR   LEU   GLY   CYSS  LEU   VAL   LYS   GLY  
TYR   PHE   PRO   GLU   PRO   VAL   THR   VAL   THR   TRP  
ASN   SER   GLY   SER   LEU   SER   SER   GLY   VAL   HISE 
THR   PHE   PRO   ALA   VAL   LEU   GLN   SER   ASP   LEU  
TYR   THR   LEU   SER   SER   SER   VAL   THR   VAL   PRO  
SER   SER   PRO   ARG   PRO   SER   GLU   THR   VAL   THR  
CYSS  ASN   VAL   ALA   HISE  PRO   ALA   SER   SER   THR  
LYS   VAL   ASP   LYS   LYS   ILE   VAL   PROT             
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                         

