Cadeia L
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
L  217    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
ASPI  VAL   LEU   MET   THR   GLN   THR   PRO   LEU   SER  
LEU   PRO   VAL   SER   LEU   GLY   ASP   GLN   ALA   SER  
ILE   SER   CYSS  ARG   PHE   SER   GLN   SER   ILE   VAL  
HISE  SER   ASN   GLY   ASN   THR   TYR   LEU   GLU   TRP  
TYR   LEU   GLN   LYS   SER   GLY   GLN   SER   PRO   LYS  
LEU   LEU   ILE   TYR   LYS   VAL   SER   ASN   ARG   PHE  
SER   GLY   VAL   PRO   ASP   ARG   PHE   SER   GLY   SER  
GLY   SER   GLY   THR   ASP   PHE   THR   LEU   LYS   ILE  
SER   ARG   VAL   GLU   ALA   GLU   ASP   LEU   GLY   VAL  
TYR   TYR   CYSS  PHE   GLN   GLY   SER   HISD  VAL   PRO  
ARG   THR   PHE   GLY   GLY   GLY   THR   LYS   LEU   GLU  
ILE   LYS   ARG   ALA   ASP   ALA   ALA   PRO   THR   VAL  
SER   ILE   PHE   PRO   PRO   SER   SER   GLU   GLN   LEU  
THR   SER   GLY   GLY   ALA   SER   VAL   VAL   CYSS  PHE  
LEU   ASN   ASN   PHE   TYR   PRO   LYS   ASP   ILE   ASN  
VAL   LYS   TRP   LYS   ILE   ASP   GLY   SER   GLU   ARG  
GLN   ASN   GLY   VAL   LEU   ASN   SER   TRP   THR   ASP  
GLN   ASP   SER   LYS   ASP   SER   THR   TYR   SER   MET  
SER   SER   THR   LEU   THR   LEU   THR   LYS   ASP   GLU  
TYR   GLU   ARG   HISD  ASN   SER   TYR   THR   CYSS  GLU  
ALA   THR   HISE  LYS   THR   SER   THR   SER   PRO   ILE  
VAL   LYS   SER   PHE   ASN   ARG   ASNT                   
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                   

