Cadeia I
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
I  141    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
LEUI  ILE   VAL   ASN   VAL   ILE   ASN   GLY   PRO   ASN  
LEU   GLY   ARG   LEU   GLY   ARG   ARG   GLU   PRO   ALA  
VAL   TYR   GLY   GLY   THR   THR   HISD  ASP   GLU   LEU  
VAL   ALA   LEU   ILE   GLU   ARG   GLU   ALA   ALA   GLU  
LEU   GLY   LEU   LYS   ALA   VAL   VAL   ARG   GLN   SER  
ASP   SER   GLU   ALA   GLN   LEU   LEU   ASP   TRP   ILE  
HISE  GLN   ALA   ALA   ASP   ALA   ALA   GLU   PRO   VAL  
ILE   LEU   ASN   ALA   GLY   GLY   LEU   THR   HISD  THR  
SER   VAL   ALA   LEU   ARG   ASP   ALA   CYSH  ALA   GLU  
LEU   SER   ALA   PRO   LEU   ILE   GLU   VAL   HISE  ILE  
SER   ASN   VAL   HISE  ALA   ARG   GLU   GLU   PHE   ARG  
ARG   HISD  SER   TYR   LEU   SER   PRO   ILE   ALA   THR  
GLY   VAL   ILE   VAL   GLY   LEU   GLY   ILE   GLN   GLY  
TYR   LEU   LEU   ALA   LEU   ARG   TYR   LEU   ALA   GLU  
HISD                                                       
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           

