Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  226    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
ILEI  ILE   GLY   GLY   GLU   PHE   THR   THR   ILE   GLU  
ASN   GLN   PRO   TRP   PHE   ALA   ALA   ILE   TYR   ARG  
ARG   HISP  VAL   THR   TYR   VAL   CYSS  GLY   GLY   SER  
LEU   MET   SER   PRO   CYSS  TRP   VAL   ILE   SER   ALA  
THR   HISD  CYSS  PHE   ILE   LYS   LYS   ASP   TYR   ILE  
VAL   TYR   LEU   GLY   ARG   SER   ARG   LEU   ASN   SER  
ASN   THR   GLN   GLY   GLU   MET   LYS   PHE   GLU   VAL  
GLU   ASN   LEU   ILE   LEU   HISD  LYS   ASP   TYR   SER  
ALA   ASP   ALA   HISE  HISE  ASN   ASP   ILE   ALA   LEU  
LEU   LYS   ILE   ARG   SER   CYSS  ALA   GLN   PRO   SER  
ARG   THR   ILE   GLN   THR   ILE   CYSH  LEU   PRO   SER  
MET   TYR   ASN   ASP   PRO   GLN   PHE   GLY   THR   SER  
CYSS  GLU   ILE   THR   GLY   PHE   GLY   LYS   GLU   ALA  
SER   THR   ASP   TYR   LEU   TYR   PRO   GLU   GLN   LEU  
LYS   MET   THR   VAL   VAL   LYS   LEU   ILE   SER   HISE 
ARG   GLU   CYSS  GLN   GLN   TYR   TYR   GLY   SER   GLU  
VAL   THR   THR   LYS   MET   LEU   CYSS  ALA   ALA   ASP  
TRP   LYS   THR   ASP   ALA   CYSS  GLN   GLY   ASP   SER  
GLY   GLY   PRO   LEU   VAL   CYSS  SER   LEU   GLN   GLY  
ARG   MET   THR   LEU   THR   GLY   ILE   VAL   SER   TRP  
GLY   ARG   GLY   CYSS  ALA   LEU   LYS   LYS   PRO   GLY  
VAL   TYR   THR   ARG   VAL   SER   HISE  PHE   LEU   PRO  
TRP   ILE   ARG   SER   HISD  THRT                         
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                             

