Cadeia L
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
L   54    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
LYSI  LEU   CYSS  SER   LEU   ASP   ASN   GLY   ASP   CYSS 
ASP   GLN   PHE   CYSS  HISP  GLU   GLU   GLN   ASN   SER  
VAL   VAL   CYSS  SER   CYSH  ALA   ARG   GLY   TYR   THR  
LEU   ALA   ASP   ASN   GLY   LYS   ALA   CYSH  ILE   PRO  
THR   GLY   PRO   TYR   PRO   CYSH  GLY   LYS   GLN   THR  
LEU   GLU   ARG   ARGT                                     
                                                           
                                                           
                                                           
                                                           
                 

