Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  155    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
ILEI  VAL   THR   GLN   THR   MET   LYS   GLY   LEU   ASP  
ILE   GLN   LYS   VAL   ALA   GLY   THR   TRP   TYR   SER  
LEU   ALA   MET   ALA   ALA   SER   ASP   ILE   SER   LEU  
LEU   ASP   ALA   GLN   SER   ALA   PRO   LEU   ARG   VAL  
TYR   VAL   GLU   GLU   LEU   LYS   PRO   THR   PRO   GLU  
GLY   ASP   LEU   GLU   ILE   LEU   LEU   GLN   LYS   TRP  
GLU   ASN   GLY   GLU   CYSS  ALA   GLN   LYS   LYS   ILE  
ILE   ALA   GLU   LYS   THR   LYS   ILE   PRO   ALA   VAL  
PHE   LYS   ILE   ASP   ALA   LEU   ASN   GLU   ASN   LYS  
VAL   LEU   VAL   LEU   ASP   THR   ASP   TYR   LYS   LYS  
TYR   LEU   LEU   PHE   CYSS  MET   GLU   ASN   SER   LEU  
ALA   CYSS  GLN   CYSH  LEU   VAL   ARG   THR   PRO   GLU  
VAL   ASP   ASP   GLU   ALA   LEU   GLU   LYS   PHE   ASP  
LYS   ALA   LEU   LYS   ALA   LEU   PRO   MET   HISD  ILE  
ARG   LEU   SER   PHE   ASN   PRO   THR   GLN   LEU   GLU  
GLU   GLN   CYSS  HISE  ILET                               
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                       

