Cadeia H
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
H  226    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
ILEI  VAL   GLU   GLY   SER   ASP   ALA   GLU   ILE   GLY  
MET   SER   PRO   TRP   GLN   VAL   MET   LEU   PHE   ARG  
LYS   PRO   GLN   GLU   LEU   LEU   CYSS  GLY   ALA   SER  
LEU   ILE   SER   ASP   ARG   TRP   VAL   LEU   THR   ALA  
ALA   HISD  CYSS  LEU   LEU   GLU   ASN   ASP   LEU   LEU  
VAL   ARG   ILE   GLY   LYS   HISE  SER   ARG   THR   ARG  
TYR   GLU   ASN   ILE   GLU   LYS   ILE   SER   MET   LEU  
GLU   LYS   ILE   TYR   ILE   HISE  PRO   ARG   TYR   ASN  
TRP   ARG   ASN   LEU   ASP   ARG   ASP   ILE   ALA   LEU  
MET   LYS   LEU   LYS   LYS   PRO   VAL   ALA   PHE   SER  
ASP   TYR   ILE   HISE  PRO   VAL   CYSH  LEU   PRO   ASP  
ARG   GLU   THR   ALA   LEU   GLN   ALA   GLY   TYR   LYS  
GLY   ARG   VAL   THR   GLY   TRP   GLY   ASN   LEU   LYS  
GLU   GLY   GLN   PRO   SER   VAL   LEU   GLN   VAL   VAL  
ASN   LEU   PRO   ILE   VAL   GLU   ARG   PRO   VAL   CYSS 
LYS   ASP   SER   THR   ARG   ILE   ARG   ILE   THR   ASP  
ASN   MET   PHE   CYSS  ALA   GLY   LYS   PRO   ARG   GLY  
ASP   ALA   CYSS  GLU   GLY   ASP   SER   GLY   GLY   PRO  
PHE   VAL   MET   LYS   SER   PRO   ASN   ARG   TRP   TYR  
GLN   MET   GLY   ILE   VAL   SER   TRP   GLY   GLU   GLY  
CYSS  ASP   ASP   GLY   LYS   TYR   GLY   PHE   TYR   THR  
HISE  VAL   PHE   ARG   LEU   LYS   LYS   TRP   ILE   GLN  
LYS   VAL   ILE   ASP   GLN   PHET                         
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                             

