Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  319    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
VALI  LYS   GLU   PHE   LEU   ALA   LYS   ALA   LYS   GLU  
ASP   PHE   LEU   LYS   LYS   TRP   GLU   ASN   PRO   ALA  
GLN   ASN   THR   ALA   HISE  LEU   ASP   GLN   PHE   GLU  
ARG   ILE   LYS   THR   LEU   GLY   THR   GLY   SER   PHE  
GLY   ARG   VAL   MET   LEU   VAL   LYS   HISE  MET   GLU  
THR   GLY   ASN   HISD  TYR   ALA   MET   LYS   ILE   LEU  
ASP   LYS   GLN   LYS   VAL   VAL   LYS   LEU   LYS   GLN  
ILE   GLU   HISD  THR   LEU   ASN   GLU   LYS   ARG   ILE  
LEU   GLN   ALA   VAL   ASN   PHE   PRO   PHE   LEU   VAL  
LYS   LEU   GLU   PHE   SER   PHE   LYS   ASP   ASN   SER  
ASN   LEU   TYR   MET   VAL   MET   GLU   TYR   VAL   PRO  
GLY   GLY   GLU   MET   PHE   SER   HISE  LEU   ARG   ARG  
ILE   GLY   ARG   PHE   SER   GLU   PRO   HISE  ALA   ARG  
PHE   TYR   ALA   ALA   GLN   ILE   VAL   LEU   THR   PHE  
GLU   TYR   LEU   HISE  SER   LEU   ASP   LEU   ILE   TYR  
ARG   ASP   LEU   LYS   PRO   GLU   ASN   LEU   LEU   ILE  
ASP   GLN   GLN   GLY   TYR   ILE   GLN   VAL   THR   ASP  
PHE   GLY   PHE   ALA   LYS   ARG   VAL   LYS   GLY   ARG  
THR   TRP   THR   LEU   CYSH  GLY   THR   PRO   GLU   TYR  
LEU   ALA   PRO   GLU   ILE   ILE   LEU   SER   LYS   GLY  
TYR   ASN   LYS   ALA   VAL   ASP   TRP   TRP   ALA   LEU  
GLY   VAL   LEU   ILE   TYR   GLU   MET   ALA   ALA   GLY  
TYR   PRO   PRO   PHE   PHE   ALA   ASP   GLN   PRO   ILE  
GLN   ILE   TYR   GLU   LYS   ILE   VAL   SER   GLY   LYS  
VAL   ARG   PHE   PRO   SER   HISE  PHE   SER   SER   ASP  
LEU   LYS   ASP   LEU   LEU   ARG   ASN   LEU   LEU   GLN  
VAL   ASP   LEU   THR   LYS   ARG   PHE   GLY   ASN   LEU  
LYS   ASN   GLY   VAL   ASN   ASP   ILE   LYS   ASN   HISE 
LYS   TRP   PHE   ALA   THR   THR   ASP   TRP   ILE   ALA  
ILE   TYR   GLN   ARG   LYS   VAL   GLU   ALA   PRO   PHE  
ILE   PRO   LYS   ILE   ARG   VAL   SER   ILE   ASN   GLU  
LYS   CYSH  GLY   LYS   GLU   PHE   SER   GLU   PHET       
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                               

