Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  209    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
ARGI  LEU   ILE   LEU   ALA   MET   ASP   LEU   MET   ASN  
ARG   ASP   ASP   ALA   LEU   ARG   VAL   THR   GLY   GLU  
VAL   ARG   GLU   TYR   ILE   ASP   THR   VAL   LYS   ILE  
GLY   TYR   PRO   LEU   VAL   LEU   SER   GLU   GLY   MET  
ASP   ILE   ILE   ALA   GLU   PHE   ARG   LYS   ARG   PHE  
GLY   CYSH  ARG   ILE   ILE   ALA   ASP   PHE   LYS   VAL  
ALA   ASP   ILE   PRO   GLU   THR   ASN   GLU   LYS   ILE  
CYSH  ARG   ALA   THR   PHE   LYS   ALA   GLY   ALA   ASP  
ALA   ILE   ILE   VAL   HISE  GLY   PHE   PRO   GLY   ALA  
ASP   SER   VAL   ARG   ALA   CYSH  LEU   ASN   VAL   ALA  
GLU   GLU   MET   GLY   ARG   GLU   VAL   PHE   LEU   LEU  
THR   GLU   MET   SER   HISE  PRO   GLY   ALA   GLU   MET  
PHE   ILE   GLN   GLY   ALA   ALA   ASP   GLU   ILE   ALA  
ARG   MET   GLY   VAL   ASP   LEU   GLY   VAL   LYS   ASN  
TYR   VAL   GLY   PRO   SER   THR   ARG   PRO   GLU   ARG  
LEU   SER   ARG   LEU   ARG   GLU   ILE   ILE   GLY   GLN  
ASP   SER   PHE   LEU   ILE   SER   PRO   GLY   VAL   GLY  
ALA   GLN   GLY   GLY   ASP   PRO   GLY   GLU   THR   LEU  
ARG   PHE   ALA   ASP   ALA   ILE   ILE   VAL   GLY   ARG  
SER   ILE   TYR   LEU   ALA   ASP   ASN   PRO   ALA   ALA  
ALA   ALA   ALA   GLY   ILE   ILE   GLU   SER   ILET       
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                               

