Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  211    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
VALI  GLN   LEU   GLN   GLN   SER   GLY   PRO   GLU   LEU  
VAL   LYS   PRO   GLY   ALA   SER   VAL   ARG   MET   SER  
CYSS  LYS   SER   SER   GLY   TYR   ILE   PHE   THR   ASP  
PHE   TYR   MET   ASN   TRP   VAL   ARG   GLN   SER   HISE 
GLY   LYS   SER   LEU   ASP   TYR   ILE   GLY   TYR   ILE  
SER   TYR   SER   GLY   VAL   THR   GLY   TYR   ASN   GLN  
LYS   PHE   LYS   GLY   LYS   ALA   THR   LEU   THR   VAL  
ASP   LYS   SER   SER   SER   THR   ALA   TYR   MET   GLU  
LEU   THR   SER   GLU   ASP   SER   ALA   VAL   TYR   TYR  
CYSS  ALA   GLY   SER   SER   GLY   ASN   LYS   TRP   ASP  
TYR   TRP   GLY   HISD  GLY   ALA   SER   VAL   THR   VAL  
SER   SER   ALA   LYS   THR   THR   ALA   PRO   SER   VAL  
TYR   PRO   LEU   ALA   PRO   VAL   CYSH  GLY   ASP   THR  
THR   GLY   SER   SER   VAL   THR   LEU   GLY   CYSS  LEU  
VAL   LYS   GLY   TYR   PHE   PRO   GLU   PRO   VAL   THR  
LEU   THR   TRP   ASN   SER   GLY   SER   LEU   SER   SER  
GLY   VAL   HISD  THR   PHE   PRO   ALA   VAL   LEU   GLN  
SER   ASP   LEU   TYR   THR   LEU   SER   SER   SER   VAL  
THR   VAL   THR   SER   SER   THR   TRP   PRO   SER   GLN  
SER   ILE   THR   CYSS  ASN   VAL   ALA   HISP  PRO   ALA  
SER   SER   THR   LYS   VAL   ASP   LYS   LYS   ILE   GLU  
PROT                                                       
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           

