Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  227    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
ALAI  ASP   LEU   ARG   ALA   LEU   ALA   LYS   HISE  LEU  
TYR   ASP   SER   TYR   ILE   LYS   SER   PHE   PRO   LEU  
THR   LYS   ALA   LYS   ALA   ARG   ALA   ILE   LEU   SER  
PRO   PHE   VAL   ILE   TYR   ASP   MET   ASN   SER   ALA  
ILE   ARG   ILE   PHE   GLN   GLY   CYSH  GLN   PHE   ARG  
SER   VAL   GLU   ALA   VAL   GLN   GLU   ILE   THR   GLU  
TYR   ALA   LYS   SER   ILE   PRO   GLY   PHE   VAL   ASN  
LEU   ASP   LEU   ASN   ASP   GLN   VAL   THR   LEU   LEU  
LYS   TYR   GLY   VAL   HISE  GLU   ILE   ILE   TYR   THR  
MET   LEU   ALA   SER   LEU   MET   ASN   LYS   ASP   GLY  
VAL   LEU   ILE   SER   GLU   GLY   GLN   GLY   PHE   MET  
THR   ARG   GLU   PHE   LEU   LYS   SER   LEU   ARG   LYS  
PRO   PHE   GLY   ASP   PHE   MET   GLU   PRO   LYSN  PHE  
GLU   PHE   ALA   VAL   LYS   PHE   ASN   ALA   LEU   GLU  
LEU   ASP   ASP   SER   ASP   LEU   ALA   ILE   PHE   ILE  
ALA   VAL   ILE   ILE   LEU   SER   GLY   ASP   ARG   PRO  
GLY   LEU   LEU   ASN   VAL   LYS   PRO   ILE   GLU   ASP  
ILE   GLN   ASP   ASN   LEU   LEU   GLN   ALA   LEU   GLU  
LEU   GLN   LEU   LYS   LEU   ASN   HISE  PRO   GLU   SER  
SER   GLN   LEU   PHE   ALA   LYS   LEU   LEU   GLN   LYS  
MET   THR   ASP   LEU   ARG   GLN   ILE   VAL   THR   GLU  
HISE  VAL   GLN   LEU   LEU   HISE  PRO   LEU   LEU   GLN  
GLU   ILE   TYR   LYS   ASP   LEU   TYRT                   
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                   

