Cadeia H
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
H  203    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
GLNI  ILE   GLN   LEU   VAL   GLN   SER   GLY   PRO   GLUN2
LEU   LYS   THR   PRO   GLY   GLU   THR   VAL   ARG   ILE  
SER   CYSS  LYS   ALA   SER   GLY   TYR   THR   PHE   THR  
THR   TYR   GLY   MET   SER   TRP   VAL   LYS   GLN   THR  
PRO   GLY   LYS   GLY   PHE   LYS   TRP   MET   GLY   TRP  
ILE   ASN   TYR   SER   GLY   VAL   PRO   THR   TYR   ALA  
ASP   ASP   PHE   LYS   GLY   ARG   PHE   ALA   PHE   SER  
LEU   GLU   THR   SER   ALA   SER   THR   ALA   TYR   LEU  
GLN   ILE   LYS   ASN   GLU   ASP   THR   ALA   THR   TYR  
PHE   CYSS  ALA   ARG   ARG   SER   TRP   ASP   VAL   TRP  
GLY   THR   GLY   THR   THR   VAL   THR   VAL   SER   SER  
ALA   LYS   THR   THR   PRO   PRO   SER   VAL   TYR   PRO  
LEU   ALA   PRO   SER   MET   VAL   THR   LEU   GLY   CYSS 
LEU   VAL   LYS   GLY   TYR   PHE   PRO   GLUN2 PRO   VAL  
THR   VAL   THR   TRP   ASN   SER   GLY   SER   LEU   SER  
SER   GLY   VAL   HISP  THR   PHE   PRO   ALA   VAL   LEU  
GLN   SER   ASP   LEU   TYR   THR   LEU   SER   SER   SER  
VAL   THR   VAL   PRO   SER   SER   THR   TRP   PRO   SER  
GLN   THR   VAL   THR   CYSS  ASN   VAL   ALA   HISP  PRO  
ALA   SER   SER   THR   LYS   VAL   ASP   LYS   LYS   ILE  
VAL   PRO   ARGT                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
           

