Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B   96    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
GLYI  SER   MET   ALA   TRP   PHE   PHE   GLY   LYS   ILE  
PRO   ARG   ALA   LYS   ALA   GLU   GLU   MET   LEU   SER  
LYS   GLN   ARG   HISD  ASP   GLY   ALA   PHE   LEU   ILE  
ARG   GLU   SER   GLU   SER   ALA   PRO   GLY   ASP   PHE  
SER   LEU   SER   VAL   LYS   PHE   GLY   ASN   ASP   VAL  
GLN   HISE  PHE   LYS   VAL   LEU   ARG   ASP   GLY   ALA  
GLY   LYS   TYR   PHE   LEU   TRP   VAL   VAL   LYS   PHE  
ASN   SER   LEU   ASN   GLU   LEU   VAL   ASP   TYR   HISD 
ARG   SER   THR   SER   VAL   SER   ARG   ASN   GLN   GLN  
ILE   PHE   LEU   ARG   ASP   ILET                         
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                             

