Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B   20    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
THRI  THR   TYR   ALA   ASP   PHE   ILE   ALA   SER   GLY  
ARG   THR   GLY   ARG   ARG   ASN   ALA   ILE   HISD  ASPT 
                                                           
                                                     

